# Use a Node.js runtime
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the Vite port and run the dev server
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]