"""Update workout models with new fields

Revision ID: 61703dd01823
Revises: 0cb86a23ea10
Create Date: 2025-11-06 20:05:44.603910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

difficulty_enum = postgresql.ENUM('beginner', 'intermediate', 'advanced', name='exercisedifficulty')
difficulty_enum.create(op.get_bind(), checkfirst=True)

muscle_group_enum = postgresql.ENUM(
    'chest', 'back', 'shoulders', 'biceps', 'triceps', 'legs', 'core', 'full_body', 'other',
    name='exercisemusclegroup'
)
muscle_group_enum.create(op.get_bind(), checkfirst=True)

goal_type_enum = postgresql.ENUM(
    'strength', 'endurance', 'flexibility', 'weight_loss', 'general_fitness',
    name='workoutgoaltype'
)
goal_type_enum.create(op.get_bind(), checkfirst=True)

# revision identifiers, used by Alembic.
revision: str = '61703dd01823'
down_revision: Union[str, Sequence[str], None] = '0cb86a23ea10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('difficulty', difficulty_enum, nullable=True))
    op.add_column('exercises', sa.Column('instructions', sa.Text(), nullable=True))
    op.alter_column(
        'exercises',
        'muscle_group',
        type_=muscle_group_enum,
        existing_type=sa.String(),  # the current type
        postgresql_using="muscle_group::text::exercisemusclegroup"  # cast existing values
    )
    op.drop_constraint(op.f('exercises_name_key'), 'exercises', type_='unique')
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.add_column('workout_logs', sa.Column('log_details_json', sa.Text(), nullable=False))
    op.alter_column('workout_logs', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('workout_logs', 'exercises_json')
    op.add_column('workout_plans',
        sa.Column('goal_type', goal_type_enum, nullable=True)
    )
    op.add_column('workout_plans', sa.Column('plan_details_json', sa.Text(), nullable=False))
    op.drop_column('workout_plans', 'exercises_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('exercises_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workout_plans', 'plan_details_json')
    op.drop_column('workout_plans', 'goal_type')
    op.add_column('workout_logs', sa.Column('exercises_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('workout_logs', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('workout_logs', 'log_details_json')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.create_unique_constraint(op.f('exercises_name_key'), 'exercises', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('exercises', 'muscle_group',
               existing_type=sa.Enum('chest', 'back', 'shoulders', 'biceps', 'triceps', 'legs', 'core', 'full_body', 'other', name='exercisemusclegroup'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('exercises', 'instructions')
    op.drop_column('exercises', 'difficulty')
    # ### end Alembic commands ###
