"""Add calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g to food_items

Revision ID: 6b83580b5695
Revises: 858e24c171bc
Create Date: 2025-10-30 18:02:42.697296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b83580b5695'
down_revision: Union[str, Sequence[str], None] = '858e24c171bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('calories_per_100g', sa.Float(), nullable=False))
    op.add_column('food_items', sa.Column('protein_per_100g', sa.Float(), nullable=False))
    op.add_column('food_items', sa.Column('carbs_per_100g', sa.Float(), nullable=False))
    op.add_column('food_items', sa.Column('fat_per_100g', sa.Float(), nullable=False))
    op.drop_column('food_items', 'calories')
    op.drop_column('food_items', 'protein')
    op.drop_column('food_items', 'carbs')
    op.drop_column('food_items', 'fat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('fat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_items', sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_items', sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_items', sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('food_items', 'fat_per_100g')
    op.drop_column('food_items', 'carbs_per_100g')
    op.drop_column('food_items', 'protein_per_100g')
    op.drop_column('food_items', 'calories_per_100g')
    # ### end Alembic commands ###
