"""Remove MealPlan table

Revision ID: 858e24c171bc
Revises: 3c5770cd810d
Create Date: 2025-10-29 22:00:29.861887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858e24c171bc'
down_revision: Union[str, Sequence[str], None] = '3c5770cd810d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_name'), table_name='meal_plans')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('items_json', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('meal_plans_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_plans_pkey'))
    )
    op.create_index(op.f('ix_meal_plans_name'), 'meal_plans', ['name'], unique=False)
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    # ### end Alembic commands ###
